<?php

return [
    'student_info' => [
        'first_name',
        'last_name',
        'middle_name',
        'home_address',
        'city_address',
        'contact_no',
        'email',
        'gender',
        'birthdate',
        'birth_address',
        'citizenship',
        'religion',
        'civil_status',
        'fathers_name',
        'fathers_occupation',
        'mothers_name',
        'mothers_occupation',
        'guardians_name',
        'guardian_contact',
        'primary',
        'primary_sy',
        'primary_awards',
        'secondary',
        'secondary_sy',
        'secondary_sy_awards',
        'senior_high',
        'senior_high_sy',
        'senior_high_awards',
    ],
    'enrollment_data' => [
        'student_id',
        'school_year_id',
        'year_level',
        'semester',
        'department_id',
        'course_id',
        'major_id',
        'section',
        'student_status',
        'enrollment_status',
    ],
];
